### ISSUE TITLE
简介里的链接似乎打不开

### ISSUE THREAD

**Issue by Lantianyou** [HalseySpicy/Hooks-Admin#2]
[hooks.spicyboy.cn](http://hooks.spicyboy.cn/) 我这里打不开，推荐用 Vercel 部署

**Comment by HalseySpicy** [comment]
你好，目前我使用的腾讯云对象存储部署的，后面我看看 Vercel

**Comment by Lantianyou** [comment]
另外，一个小建议，尝试 reudx-toolkit 而不是 redux

**Comment by HalseySpicy** [comment]
reudx-toolkit 迁移已完成
