### ISSUE TITLE
项目运行时候报错

### ISSUE THREAD

**Issue by qiqixyq** [HalseySpicy/Hooks-Admin#21]
项目运行时候报错，麻烦各位大佬帮我看看，这个报错是vite导致的吗

![35N)FQ0YBZNL%A$3L4`0%MF](https://user-images.githubusercontent.com/25995909/187510992-4e311867-1dea-4da1-a2e0-4ae114e5e756.png)

**Comment by qiqixyq** [comment]
不好意思  这个问题我自己疏忽了，nvm没有切换node版本   明天上午 我切换版本再试一下 没有问题我就关掉这个问题

**Comment by HalseySpicy** [comment]
Node 版本大于16，重新安装依赖就没问题了

**Comment by qiqixyq** [comment]
是的，已经没问题了，谢谢
