### ISSUE TITLE
想请教一下antd语言是怎么处理的

### ISSUE THREAD

**Issue by azzlzzxz** [HalseySpicy/Hooks-Admin#7]
vite里可以吧antd的moment替换成dayjs吗？
我这边试了下，日期组件，中文不生效呀，采用的是antd提供的方案。

**Comment by HalseySpicy** [comment]
官方文档存在问题，自己引入这个就可以了
![image](https://user-images.githubusercontent.com/51069636/181719072-aee70ae3-7944-4b92-84ad-b8b25c3cd198.png)

**Comment by azzlzzxz** [comment]
感谢
